modules = {
    'Module 1': {
        'weather': '天气',
        'like': '像，如同',
        "What's the weather like?": '天气怎么样？',
        'sunny': '阳光充足的，阳光明媚的',
        'windy': '有风的，刮风的',
        'take': '带，拿',
        'cap': '（有帽檐的）帽子',
        'sofa': '沙发',
        'street': '街道',
        'rain': '下雨；雨',
        'snow': '下雪',
        'ski': '滑雪',
    },
    'Module 2': {
        'radio': '收音机；电台节目',
        'photo': '照片',
        'newspaper': '报纸',
        'little': '年幼的，幼小的',
        'camera': '照相机',
        'smile': '微笑',
        'draw': '绘画，画',
        'picture': '画面；照片',
        'write': '写',
        'letter': '信',
        'colour': '给……着色',
    },
    'Module 3': {
        'tidy': '整理，收拾',
        'room': '房间',
        'do': '做，干',
        'homework': '家庭作业',
        'sleep': '睡觉',
        'secret': '秘密',
        'card': '贺卡',
        'flower': '花',
        'science': '科学',
        'today': '今天',
    },
    'Module 4': {
        'call': '打电话，通话',
        'noise': '声音，响声',
        'drink': '喝，饮',
        'talk': '说话，交谈',
        'stone': '石子，石头',
        'five-stones': '抛接五块小石的游戏',
        'behind': '在……后面',
        'hide': '躲藏',
        'seek': '寻找',
        'hide-and-seek': '捉迷藏',
    },
    'Module 5': {
        'skip': '跳绳',
        'hurry up': '赶快',
        'late': '晚的，迟的',
        'sad': '伤心的，难过的',
        'no': '没有',
        'those': '那些',
        'clap': '拍手',
        'game': '游戏',
        'clapping game': '拍手游戏',
        'well': '嗯，喔，好',
        'kid': '小孩',
    },
    'Module 6': {
        'catch': '抓，捉；追人游戏',
        'of course': '当然',
        'usually': '通常地',
        'us': '（宾格）我们',
        'ride': '骑',
        'thing': '事物，活动',
        'ill': '有病的',
        'cook': '做（饭），烧（菜）',
        'her': '（宾格）她',
        'go shopping': '去购物',
        'kitchen': '厨房',
    },
    'Module 7': {
        "Children's Day": '儿童节',
        'TV': '电视台',
        'play': '（戏剧）演出',
        'say': '念，朗诵',
        'poem': '诗',
        'dragon': '龙',
        'dragon dance': '舞龙',
        'picnic': '野餐',
        'family': '家，家庭',
        'beach': '海滩',
    },
    'Module 8': {
        'hill': '小山',
        'past': '经过',
        'station': '车站',
        'hospital': '医院',
        'stop': '停止',
        'turn': '转向，转弯',
        'around': '到另一面，转向',
        'turn around': '转身，回转',
        'ground': '地面',
        'again': '又一次，再一次',
        'jump': '跳跃',
        'back': '回到，返回',
        'come back': '回来',
    },
    'Module 9': {
        'left': '向左；左边的',
        'turn left': '向左转',
        'right': '向右；右边的',
        'turn right': '向右转',
        'road': '公路，道路',
        'excuse me': '劳驾，对不起',
        'straight': '直地，直线地',
        'go straight on': '直着走',
        'lost': '迷路的',
        'out': '出，向外',
        'factory': '工厂',
    },
    'Module 10': {
        'next to': '接近，靠近',
        'cousin': '堂（表）兄弟姐妹',
        'supermarket': '超市',
        'wrong': '不正确的，错误的',
        'way': '道路，路线',
        'turn back': '往回走',
        'front': '前面',
        'in front of': '在……的前面',
        'well': '完全地，充分地',
        'taxi': '出租车，计程车',
        'Mrs': '太太，夫人',
        'cinema': '电影院',
    },
}
