modules = {
    'Module 1': {
        'song': '歌曲',
        'come on': '加油；快点',
        'team': '球队，运动队',
    },
    'Module 2': {
        'meat': '肉',
        'noodles': '面条',
        'rice': '米饭',
        'sweets': '糖果',
        'children': '孩子们',
        'ginger': '姜',
        'nice': '好的',
        'mm': '嗯',
        'onion': '洋葱',
        'ice cream': '冰淇淋',
    },
    'Module 3': {
        'banana': '香蕉',
        'apple': '苹果',
        'milk': '奶，牛奶',
        'orange': '橙子，橙',
        'fruit': '水果',
        'milkshake': '奶昔',
        'Here you are.': '给你',
        'everything': '每件事，所有事物',
        'tomato': '番茄，西红柿',
        'really': '很，非常',
        'their': '他（她/它）们的',
        'favourite': '最喜欢的事物',
    },
    'Module 4': {
        'T-shirt': 'T恤衫',
        'here’s': '这是',
        'hm': '嗯，唔',
        'dress': '连衣裙',
        'too': '太……',
        'one': '一个',
        'doesn’t': '不',
        'trousers': '裤子',
        'party': '聚会',
    },
    'Module 5': {
        'get up': '起床',
        'poster': '海报，招贴画',
        'go to school': '去上学',
        'have': '吃，喝',
        'lunch': '午餐',
        'have lunch': '吃午餐',
        'home': '家',
        'go home': '回家',
        'watch': '观看',
        'TV': '电视，电视机',
        'watch TV': '看电视',
    },
    'Module 6': {
        'on': '在……的时候',
        'Sunday': '星期日',
        'park': '公园',
        'great': '太好了，好极了',
        'goal': '进球，得分',
        'hooray': '好，好哇',
        'live': '居住',
        'moon': '月亮',
        'sky': '天，天空',
        'city': '城市',
    },
    'Module 7': {
        'how': '怎样，如何',
        'train': '火车',
        'chug': '发出咔哧声',
        'bus': '公共汽车',
        'beep': '（汽车喇叭）嘟嘟声',
        'by': '乘，坐（交通工具）',
        'walk': '步行',
        'How about...？': '怎么样？',
        'goes': '去',
        'work': '工作地点；工作',
        'go to work': '去上班',
        'bike': '自行车',
        'with': '与……在一起；同；跟；和',
        'run': '跑，奔跑',
        'holiday': '假期',
        'on holiday': '度假',
        'then': '然后',
        'ship': '轮船',
        'plane': '飞机',
        'love': '喜欢',
    },
    'Module 8': {
        'watches': '观看',
        'weekend': '周末',
        'read': '阅读',
        'come': '来',
        'play': '演奏（乐器）',
        'piano': '钢琴',
        'music': '音乐',
        'listen': '听',
        'listen to...': '听……',
        'CD': '激光唱片',
        'drum': '鼓',
    },
    'Module 9': {
        'winter': '冬天',
        'fly': '放飞（风筝）',
        'in': '在……期间，在……时候',
        'spring': '春天',
        'summer': '夏天',
        'autumn': '秋天',
        'skating': '滑冰',
        'go skating': '去滑冰',
        'warm': '温暖的',
        'wear': '穿，戴',
        'jacket': '夹克，短上衣',
        'sunglasses': '太阳镜',
        'cool': '凉爽的；酷的',
        'sweater': '毛线衫',
        'glove': '手套',
        'cold': '寒冷的',
        'coat': '外套',
    },
    'Module 10': {
        'year': '年，年份',
        'Happy New Year!': '新年快乐！',
        'come in': '进来',
        'present': '礼物',
        'dumpling': '水饺',
        'eat': '吃',
        'Chinese': '中国的',
        'hair': '头发',
        'firecracker': '鞭炮，爆竹',
        'have': '有',
        'Christmas': '圣诞节',
        'wish': '祝，祝愿',
        'dinner': '正餐，主餐',
    },
}
