modules = {
    'Module 1': {
        'friend': '友好的，亲切的',
        'always': '总是，一直',
        'a bit': '稍微，有点儿',
        'shy': '害羞的，胆怯的，腼腆的',
        'e-card': '电子贺卡',
        'quiet': '文静的',
        'another': '另一个，再一个',
        'him': '（宾格）他',
        'parrot': '鹦鹉',
        'twenty': '二十',
        'helpful': '肯帮忙的；有用的',
        'maths': '数学；数学课',
        'plus': '加，加上',
        'more': '更多的；另外的；附加的',
    },
    'Module 2': {
        'about': '关于',
        'river': '河',
        'wide': '宽的，宽阔的；宽广的',
        'old': '年代久的，古老的',
        'clock': '钟，时钟',
        'wheel': '轮子',
    },
    'Module 3': {
        'round': '圆形的；球形的',
        'will': '将，将会',
        'you’ll': 'you will 你将',
        'tower': '塔',
        'bridge': '桥',
        'won’t': 'will not 将不',
        'countryside': '农村，乡下',
        'farmer': '农民；农场主',
        'there': '在那里',
        'lots of': '许多的，大量的',
        'breakfast': '早餐',
        'have breakfast': '吃早餐',
        'tea': '茶；茶叶',
        'tea party': '（下午的）茶会，茶话会',
    },
    'Module 4': {
        'pick': '采，摘（花，水果）',
        'fourteen': '十四',
        'sixteen': '十六',
        'eighteen': '十八',
        'thirteen': '十三',
    },
    'Module 5': {
        'fifteen': '十五',
        'seventeen': '十七',
        'nineteen': '十九',
        'afraid': '担心的',
        'feel': '感觉；觉得',
        'all right': '好，行',
        'tomorrow': '明天',
        'Monday': '星期一',
        'why': '为什么',
        'Why not?': '为什么不呢？',
        'Tuesday': '星期二',
        'Wednesday': '星期三',
        'Thursday': '星期四',
        'next': '下一个的；其次的',
        'week': '周，星期',
    },
    'Module 6': {
        'stamp': '跺脚，用力踩',
        'computer': '计算机，电脑',
        'shall': '该，要',
        'arm': '胳膊',
    },
    'Module 7': {
        'class': '班级',
        'any': '一些，若干；任何一个',
        'ask': '问；询问；打听',
        'question': '问题',
        'forty': '四十',
        'so': '因此',
        'about': '大约',
        'thirty': '三十',
    },
    'Module 8': {
        'hard': '努力地',
        'lazy': '懒惰的；懒散的',
        'parent': '母亲；父亲',
        'Parents’ Day': '家长日',
        'speak': '谈话；说',
        'with': '对于',
        'quite': '很，非常',
        'good at': '擅长',
        'English': '英语；英语课',
        'PE = physical education': '体育；体育课',
    },
    'Module 9': {
        'Chinese': '汉语，中文；语文课',
        'art': '美术；艺术；美术课',
        'report': '成绩报告单',
        'try': '尝试，试图',
        'were': '（are的过去式）是',
        'young': '年轻的',
        'beautiful': '漂亮的，美丽的',
        'was': '（is的过去式）是',
        'also': '也，还',
        'then': '那时',
        'who': '谁',
        'grandparent': '（外）祖父；（外）祖母',
        'old': '老的，年老的',
        'yesterday': '昨天',
        'weren’t': 'were not 不是',
        'wasn’t': 'was not 不是',
        'fun': '有趣的事',
    },
    'Module 10': {
        'second': '第二',
        'floor': '层',
        'worried': '担忧的；焦虑的',
        'find': '发现，找到',
        'first': '第一',
        'remember': '记起；回想起',
        'Mother’s Day': '母亲节',
        'vegetable': '蔬菜',
        'last': '上一个',
    },
}
