# words.py
modules = {
    'Module 1': {
        'dear': '亲爱的',
        'well': '好，健康的',
        'of': '...的',
        'soon': '不久，很快',
        'tell': '告诉，说起',
        'love': '爱你的',
    },
    'Module 2': {
        'skirt': '裙子',
        'clean': '打扫，清理',
        'finish': '完成',
        'dirty': '脏的',
        'paint': '绘画',
        'Mr': '先生',
        'phone': '打电话',
    },
    'Module 3': {
        "didn't": '不',
        'National Day': '国庆节',
        'stay': '停留',
        'what': '什么',
        'boring': '无聊的; 令人厌烦的',
        'day': '天; 白天',
    },
    'Module 4': {
        'invent': '发明, 创造',
        'paper': '纸',
        'important': '重要的',
        'print': '印刷',
        'printing': '印刷术',
        'right': '正确的, 对的',
        'between': '在...之间',
        'bicycle': '自行车',
        'mouse': '老鼠',
        'beside': '在...旁边',
        'man': '男人',
    },
    'Module 5':{
        "went": "去（过去时态）",
        "saw": "看见（过去时态）",
        "trip": "出行, 旅行",
        "took": "拿起, 拍摄",
        "fifty": "五十",
        "minute": "分钟",
        "top": "顶部",
        "mountain": "山",
        "ate": "吃",
        "candies": "糖果",
        "plant": "植物",
        "had": "拥有",
        "have a good time": "过得很愉快",
        "bought": "买",
        "wore": "穿",
        "go on a trip": "去旅行",
        "ice": "冰",
        "at first": "起初, 开始时",
        "fell": "跌倒",
        "fall over": "摔倒",
        "hurt": "伤害",
        "a lot": "很多, 大量",
        "able": "有能力的",
        "be able to": "能够",
        "skate": "滑冰",
    }
}
