modules = {
    'Module 1': {
        'use': '使用',
        'chopsticks': '（常复）筷子',
        'want': '想要',
        'hungry': '饥饿的',
        'mess': '肮脏，凌乱',
        'hard': '困难的',
        'knife': '刀',
        'fork': '叉',
        'a knife and fork': '一副刀叉',
        'easy': '容易的',
        'hamburger': '汉堡包',
        'chips': '（常复）炸薯条',
        'grass': '草',
        'food': '食物',
        'fast food': '快餐',
        'quiet': '安静的，不出声的',
        'water': '给（植物）浇水；水',
        'lovely': '可爱的',
    },
    'Module 2': {
        'make': '制作',
        'cake': '蛋糕',
        'mum': '妈妈',
        'dad': '爸爸',
    },
    'Module 3': {
        'naughty': '淘气的',
        'paper': '纸做的，纸质的',
        'boat': '小船，小舟',
        'dragon boat': '龙舟',
        'people': '人，人们',
        'row': '划（船）',
        'lake': '湖',
        'feed': '喂，为……提供食物',
        'bread': '面包',
        'get out': '走开，离开',
    },
    'Module 4': {
        'far': '远',
        'fast': '快，快速地',
        'winner': '胜利者',
        'can’t': 'cannot 不能',
    },
    'Module 5': {
        'slow': '慢的',
        'fly': '飞',
        'koala': '树袋熊，考拉',
        'climb': '爬',
        'cry': '哭',
        'pear': '梨',
        'peach': '桃子',
        'drink': '一杯（份）饮料',
        'shop': '商店',
        'go out': '外出',
        'thanks': '谢谢',
        'library': '图书馆，图书室',
        'worry': '担心',
    },
    'Module 6': {
        'have got': '有',
        'careful': '小心的',
        'wash': '洗',
        'has got': '（have got的第三人称单数形式）有',
    },
    'Module 7': {
        'headache': '头痛',
        'stomach ache': '胃痛；腹痛',
        'test': '考试',
        'Friday': '星期五',
        'clever': '聪明的',
        'cold': '感冒',
        'class': '课',
        'begin': '开始',
        'cough': '咳嗽',
    },
    'Module 8': {
        'bring': '带来',
        'umbrella': '雨伞',
        'get': '拿，取',
        'which': '哪一个',
        'broken': '损坏的',
    },
    'Module 9': {
        'long jump': '跳远',
        'make friends': '交朋友',
        'sports day': '运动日',
        'high': '高的',
        'high jump': '跳高',
        'race': '赛跑',
        'run a race': '（参加）赛跑',
        'star': '明星；星',
        'uncle': '伯父；叔父；舅父；姑父；姨父',
    },
    'Module 10': {
        'airport': '飞机场',
        'sea': '大海',
        'visit': '拜访（某人），参观（某地）',
        'Saturday': '星期六',
        'film': '电影',
    },
}
