# words.py
modules = {
    'Module 1': {
        'dear': '亲爱的',
        'well': '好，健康的',
        'of': '什么什么的',
        'soon': '不久，很快',
        'tell': '告诉，说起',
        'love': '爱你的',
    },
    'Module 2': {
        'skirt': '裙子',
        'clean': '打扫，清理',
        'finish': '完成',
        'dirty': '脏的',
        'paint': '绘画',
        'Mr': '先生',
        'phone': '打电话',
    },
    'Module 3': {
        "didn't": '不',
        'National Day': '国庆节',
        'stay': '停留',
        'what': '什么',
        'boring': '无聊的; 令人厌烦的',
        'day': '天; 白天',
    },
    'Module 4': {
        'invent': '发明, 创造',
        'paper': '纸',
        'important': '重要的',
        'print': '印刷',
        'printing': '印刷术',
        'right': '正确的, 对的',
        'between': '在...之间',
        'bicycle': '自行车',
        'mouse': '老鼠',
        'beside': '在...旁边',
        'man': '男人',
    },
    'Module 5':{
        "went": "去（过去时态）",
        "saw": "看见（过去时态）",
        "trip": "出行, 旅行",
        "took": "take 的过去式，需要花费",
        "fifty": "五十",
        "minute": "分钟",
        "top": "顶部",
        "mountain": "山",
        "ate": "吃（过去时态）",
        "candies": "糖果",
        "plant": "植物",
        "had": "拥有",
        "have a good time": "过得很愉快",
        "bought": "买",
        "wore": "穿",
        "go on a trip": "去旅行",
        "ice": "冰",
        "at first": "起初, 开始时",
        "fell": "跌倒",
        "fall over": "摔倒",
        "hurt": "伤害",
        "a lot": "很多, 大量",
        "able": "有能力的",
        "be able to": "能够",
        "skate": "滑冰",
    },
        "Module 6": {
        "become": "变成",
        "gold": "金子",
        "ago": "以前, 以往",
        "long ago": "很久以前",
        "magic": "有魔力的",
        "paintbrush": "画笔",
        "woman": "妇女, 女性",
        "became": "变成（过去时态）",
        "real": "真实的",
        "bad": "坏的, 不好的",
        "took": "拿走（过去时态）",
        "away": "离去, 离开",
        "leaves": "叶子",
        "only": "只, 仅仅",
        "painting": "画; 画作",
        "angry": "生气的, 愤怒的",
        "said": "说（过去时态）"
    },
    "Module 7": {
        "doll": "玩偶, 娃娃模特",
        "matter": "事情",
        "lost": "丢失",
        "found": "找到",
        "key": "钥匙",
        "look for": "寻找"
    },
    "Module 8": {
        "when": "什么时候",
        "came": "来",
        "competition": "比赛",
        "won": "赢, 获胜",
        "gold": "金制的",
        "cup": "奖杯",
        "flute": "长笛",
        "practise": "练习",
        "took": "拿",
        "look": "看上去...",
        "a lot": "经常, 长时间地"
    },
    "Module 9": {
        "happen": "发生",
        "fall off": "从...掉落",
        "bike ride": "骑自行车",
        "thirsty": "渴",
        "water": "水",
        "watermelon": "西瓜",
        "carried": "携带",
        "bump": "碰, 撞",
        "hurt": "伤害; 使疼痛",
        "knee": "膝盖",
        "cut": "切, 割",
        "finger": "手指"
    },
    "Module 10": {
        "early": "早",
        "every": "每个, 每一",
        "during": "在...期间",
        "computer game": "计算机游戏",
        "take": "服（药）",
        "medicine": "药",
        "a lot of": "许多的",
        "exercise": "运动, 锻炼",
        "salad": "色拉, 凉拌菜",
        "healthy": "有益健康的; 健康的",
        "juice": "果汁",
        "before": "在......之前",
        "after": "在......之后",
        "toilet": "厕所"
    }
}
